#!/usr/bin/env bash

if [ "$#" -lt 1 ]; then
    MSG="yo"
else
    MSG="$1"
fi

REQ_ID=$(uuidgen)

ACK_CMD="curl $DAWG_URL/ack/$REQ_ID"

# First arm the request on the server
curl  --get "$DAWG_URL/arm/$REQ_ID" \
    --data-urlencode "message=$MSG" --data-urlencode "username=$DAWG_USER"

# Now send the local notification with callback to disarm
terminal-notifier -message "$MSG" -title dawg -execute "$ACK_CMD"
